name: Counting Detected Objects in NYC Traffic Cam Footage

on:
  schedule:
    - cron: '*/15 * * * *' # Run every 15 minutes

jobs:

  detect-objects:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 torch torchvision pycocotools
        
    - name: Run Object Detection Script
      run: |
        python detect_objects.py
        
    - name: Commit and Push Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Storing Detected Objects in DB
        file_pattern: detections.db
